-- [DEPRECATED] Old tall-format get_aggregated_telemetry removed.
-- The compact wide-format definition is now the source of truth in:
--   20250603_aggregation_compact.sql  (original)
--   20250604_aggregation_definitive.sql  (canonical, with coalesce)
--
-- If you need to recreate the function, apply the 20250604 migration.
