/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TELEMETRY_PB_H_INCLUDED
#define PB_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(24) TelemetryDevice_id_t;
typedef PB_BYTES_ARRAY_T(16) TelemetryDevice_fw_t;
typedef struct _TelemetryDevice {
    TelemetryDevice_id_t id;
    TelemetryDevice_fw_t fw;
    uint32_t uptime_ms;
} TelemetryDevice;

typedef PB_BYTES_ARRAY_T(16) TelemetryWifi_ip_t;
typedef struct _TelemetryWifi {
    int32_t rssi;
    TelemetryWifi_ip_t ip;
} TelemetryWifi;

typedef struct _TelemetryChannel {
    uint32_t ch;
    float V;
    float I;
    float P;
    float energy_Wh;
    float charge_mAh;
} TelemetryChannel;

typedef struct _TelemetrySwitch {
    uint32_t idx;
    uint32_t type;
    bool state;
    bool auto_mode;
    bool rule_tripped;
} TelemetrySwitch;

typedef struct _TelemetryBattery {
    uint32_t ch;
    uint32_t profile_id;
    uint32_t chemistry;
    float rated_Ah;
    float soc_pct;
    float V;
    float I;
    float cumulative_Ah_in;
    float cumulative_Ah_out;
    float equivalent_full_cycles;
    float soh_pct;
    uint32_t soh_samples;
} TelemetryBattery;

typedef struct _TelemetryLogMeta {
    uint32_t entries;
    bool overflow;
} TelemetryLogMeta;

typedef PB_BYTES_ARRAY_T(16) TelemetrySnapshot_schema_t;
typedef struct _TelemetrySnapshot {
    uint32_t ts;
    uint32_t ts_ms;
    uint32_t schema_version;
    TelemetrySnapshot_schema_t schema;
    bool has_device;
    TelemetryDevice device;
    bool has_wifi;
    TelemetryWifi wifi;
    uint32_t channel_count;
    uint32_t switch_count;
    uint32_t num_batteries;
    pb_size_t channels_count;
    TelemetryChannel channels[16];
    pb_size_t switches_count;
    TelemetrySwitch switches[8];
    pb_size_t battery_count;
    TelemetryBattery battery[8];
    bool has_log;
    TelemetryLogMeta log;
    uint32_t heap_free;
} TelemetrySnapshot;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TelemetryDevice_init_default             {{0, {0}}, {0, {0}}, 0}
#define TelemetryWifi_init_default               {0, {0, {0}}}
#define TelemetryChannel_init_default            {0, 0, 0, 0, 0, 0}
#define TelemetrySwitch_init_default             {0, 0, 0, 0, 0}
#define TelemetryBattery_init_default            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define TelemetryLogMeta_init_default            {0, 0}
#define TelemetrySnapshot_init_default           {0, 0, 0, {0, {0}}, false, TelemetryDevice_init_default, false, TelemetryWifi_init_default, 0, 0, 0, 0, {TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default, TelemetryChannel_init_default}, 0, {TelemetrySwitch_init_default, TelemetrySwitch_init_default, TelemetrySwitch_init_default, TelemetrySwitch_init_default, TelemetrySwitch_init_default, TelemetrySwitch_init_default, TelemetrySwitch_init_default, TelemetrySwitch_init_default}, 0, {TelemetryBattery_init_default, TelemetryBattery_init_default, TelemetryBattery_init_default, TelemetryBattery_init_default, TelemetryBattery_init_default, TelemetryBattery_init_default, TelemetryBattery_init_default, TelemetryBattery_init_default}, false, TelemetryLogMeta_init_default, 0}
#define TelemetryDevice_init_zero                {{0, {0}}, {0, {0}}, 0}
#define TelemetryWifi_init_zero                  {0, {0, {0}}}
#define TelemetryChannel_init_zero               {0, 0, 0, 0, 0, 0}
#define TelemetrySwitch_init_zero                {0, 0, 0, 0, 0}
#define TelemetryBattery_init_zero               {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define TelemetryLogMeta_init_zero               {0, 0}
#define TelemetrySnapshot_init_zero              {0, 0, 0, {0, {0}}, false, TelemetryDevice_init_zero, false, TelemetryWifi_init_zero, 0, 0, 0, 0, {TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero, TelemetryChannel_init_zero}, 0, {TelemetrySwitch_init_zero, TelemetrySwitch_init_zero, TelemetrySwitch_init_zero, TelemetrySwitch_init_zero, TelemetrySwitch_init_zero, TelemetrySwitch_init_zero, TelemetrySwitch_init_zero, TelemetrySwitch_init_zero}, 0, {TelemetryBattery_init_zero, TelemetryBattery_init_zero, TelemetryBattery_init_zero, TelemetryBattery_init_zero, TelemetryBattery_init_zero, TelemetryBattery_init_zero, TelemetryBattery_init_zero, TelemetryBattery_init_zero}, false, TelemetryLogMeta_init_zero, 0}

/* Field tags (for use in manual encoding/decoding) */
#define TelemetryDevice_id_tag                   1
#define TelemetryDevice_fw_tag                   2
#define TelemetryDevice_uptime_ms_tag            3
#define TelemetryWifi_rssi_tag                   1
#define TelemetryWifi_ip_tag                     2
#define TelemetryChannel_ch_tag                  1
#define TelemetryChannel_V_tag                   2
#define TelemetryChannel_I_tag                   3
#define TelemetryChannel_P_tag                   4
#define TelemetryChannel_energy_Wh_tag           5
#define TelemetryChannel_charge_mAh_tag          6
#define TelemetrySwitch_idx_tag                  1
#define TelemetrySwitch_type_tag                 2
#define TelemetrySwitch_state_tag                3
#define TelemetrySwitch_auto_mode_tag            4
#define TelemetrySwitch_rule_tripped_tag         5
#define TelemetryBattery_ch_tag                  1
#define TelemetryBattery_profile_id_tag          2
#define TelemetryBattery_chemistry_tag           3
#define TelemetryBattery_rated_Ah_tag            4
#define TelemetryBattery_soc_pct_tag             5
#define TelemetryBattery_V_tag                   6
#define TelemetryBattery_I_tag                   7
#define TelemetryBattery_cumulative_Ah_in_tag    8
#define TelemetryBattery_cumulative_Ah_out_tag   9
#define TelemetryBattery_equivalent_full_cycles_tag 10
#define TelemetryBattery_soh_pct_tag             11
#define TelemetryBattery_soh_samples_tag         12
#define TelemetryLogMeta_entries_tag             1
#define TelemetryLogMeta_overflow_tag            2
#define TelemetrySnapshot_ts_tag                 1
#define TelemetrySnapshot_ts_ms_tag              2
#define TelemetrySnapshot_schema_version_tag     3
#define TelemetrySnapshot_schema_tag             4
#define TelemetrySnapshot_device_tag             5
#define TelemetrySnapshot_wifi_tag               6
#define TelemetrySnapshot_channel_count_tag      7
#define TelemetrySnapshot_switch_count_tag       8
#define TelemetrySnapshot_num_batteries_tag      9
#define TelemetrySnapshot_channels_tag           10
#define TelemetrySnapshot_switches_tag           11
#define TelemetrySnapshot_battery_tag            12
#define TelemetrySnapshot_log_tag                13
#define TelemetrySnapshot_heap_free_tag          14

/* Struct field encoding specification for nanopb */
#define TelemetryDevice_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    id,                1) \
X(a, STATIC,   SINGULAR, BYTES,    fw,                2) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_ms,         3)
#define TelemetryDevice_CALLBACK NULL
#define TelemetryDevice_DEFAULT NULL

#define TelemetryWifi_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              1) \
X(a, STATIC,   SINGULAR, BYTES,    ip,                2)
#define TelemetryWifi_CALLBACK NULL
#define TelemetryWifi_DEFAULT NULL

#define TelemetryChannel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ch,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    V,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    I,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    P,                 4) \
X(a, STATIC,   SINGULAR, FLOAT,    energy_Wh,         5) \
X(a, STATIC,   SINGULAR, FLOAT,    charge_mAh,        6)
#define TelemetryChannel_CALLBACK NULL
#define TelemetryChannel_DEFAULT NULL

#define TelemetrySwitch_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   idx,               1) \
X(a, STATIC,   SINGULAR, UINT32,   type,              2) \
X(a, STATIC,   SINGULAR, BOOL,     state,             3) \
X(a, STATIC,   SINGULAR, BOOL,     auto_mode,         4) \
X(a, STATIC,   SINGULAR, BOOL,     rule_tripped,      5)
#define TelemetrySwitch_CALLBACK NULL
#define TelemetrySwitch_DEFAULT NULL

#define TelemetryBattery_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ch,                1) \
X(a, STATIC,   SINGULAR, UINT32,   profile_id,        2) \
X(a, STATIC,   SINGULAR, UINT32,   chemistry,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    rated_Ah,          4) \
X(a, STATIC,   SINGULAR, FLOAT,    soc_pct,           5) \
X(a, STATIC,   SINGULAR, FLOAT,    V,                 6) \
X(a, STATIC,   SINGULAR, FLOAT,    I,                 7) \
X(a, STATIC,   SINGULAR, FLOAT,    cumulative_Ah_in,   8) \
X(a, STATIC,   SINGULAR, FLOAT,    cumulative_Ah_out,   9) \
X(a, STATIC,   SINGULAR, FLOAT,    equivalent_full_cycles,  10) \
X(a, STATIC,   SINGULAR, FLOAT,    soh_pct,          11) \
X(a, STATIC,   SINGULAR, UINT32,   soh_samples,      12)
#define TelemetryBattery_CALLBACK NULL
#define TelemetryBattery_DEFAULT NULL

#define TelemetryLogMeta_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   entries,           1) \
X(a, STATIC,   SINGULAR, BOOL,     overflow,          2)
#define TelemetryLogMeta_CALLBACK NULL
#define TelemetryLogMeta_DEFAULT NULL

#define TelemetrySnapshot_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ts,                1) \
X(a, STATIC,   SINGULAR, UINT32,   ts_ms,             2) \
X(a, STATIC,   SINGULAR, UINT32,   schema_version,    3) \
X(a, STATIC,   SINGULAR, BYTES,    schema,            4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device,            5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wifi,              6) \
X(a, STATIC,   SINGULAR, UINT32,   channel_count,     7) \
X(a, STATIC,   SINGULAR, UINT32,   switch_count,      8) \
X(a, STATIC,   SINGULAR, UINT32,   num_batteries,     9) \
X(a, STATIC,   REPEATED, MESSAGE,  channels,         10) \
X(a, STATIC,   REPEATED, MESSAGE,  switches,         11) \
X(a, STATIC,   REPEATED, MESSAGE,  battery,          12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  log,              13) \
X(a, STATIC,   SINGULAR, UINT32,   heap_free,        14)
#define TelemetrySnapshot_CALLBACK NULL
#define TelemetrySnapshot_DEFAULT NULL
#define TelemetrySnapshot_device_MSGTYPE TelemetryDevice
#define TelemetrySnapshot_wifi_MSGTYPE TelemetryWifi
#define TelemetrySnapshot_channels_MSGTYPE TelemetryChannel
#define TelemetrySnapshot_switches_MSGTYPE TelemetrySwitch
#define TelemetrySnapshot_battery_MSGTYPE TelemetryBattery
#define TelemetrySnapshot_log_MSGTYPE TelemetryLogMeta

extern const pb_msgdesc_t TelemetryDevice_msg;
extern const pb_msgdesc_t TelemetryWifi_msg;
extern const pb_msgdesc_t TelemetryChannel_msg;
extern const pb_msgdesc_t TelemetrySwitch_msg;
extern const pb_msgdesc_t TelemetryBattery_msg;
extern const pb_msgdesc_t TelemetryLogMeta_msg;
extern const pb_msgdesc_t TelemetrySnapshot_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TelemetryDevice_fields &TelemetryDevice_msg
#define TelemetryWifi_fields &TelemetryWifi_msg
#define TelemetryChannel_fields &TelemetryChannel_msg
#define TelemetrySwitch_fields &TelemetrySwitch_msg
#define TelemetryBattery_fields &TelemetryBattery_msg
#define TelemetryLogMeta_fields &TelemetryLogMeta_msg
#define TelemetrySnapshot_fields &TelemetrySnapshot_msg

/* Maximum encoded size of messages (where known) */
#define TELEMETRY_PB_H_MAX_SIZE                  TelemetrySnapshot_size
#define TelemetryBattery_size                    64
#define TelemetryChannel_size                    31
#define TelemetryDevice_size                     50
#define TelemetryLogMeta_size                    8
#define TelemetrySnapshot_size                   1364
#define TelemetrySwitch_size                     18
#define TelemetryWifi_size                       24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
