/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "telemetry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TelemetryDevice, TelemetryDevice, AUTO)


PB_BIND(TelemetryWifi, TelemetryWifi, AUTO)


PB_BIND(TelemetryChannel, TelemetryChannel, AUTO)


PB_BIND(TelemetrySwitch, TelemetrySwitch, AUTO)


PB_BIND(TelemetryBattery, TelemetryBattery, AUTO)


PB_BIND(TelemetryLogMeta, TelemetryLogMeta, AUTO)


PB_BIND(TelemetrySnapshot, TelemetrySnapshot, 2)



